<?php
/**
  * DCubeClient PHP output file
  * autogenerated using DCube 7.5.1 by Krzysztof Daniel Ciba (Krzysztof.Ciba@NOSPAMgmail.com)
  * on Tue, 28 Jul 2026 11:17:01 CEST
  * Files:
  * [1] monitored file  = idtpm.HIST.root
  * [2] reference file  = physval_tmp.ntuple.IDTPMcnv.root
  * [3] config XML file = /cvmfs/atlas-nightlies.cern.ch/repo/sw/main_Athena_x86_64-el9-gcc14-opt/2026-07-14T2100/Athena/25.0.68/InstallArea/x86_64-el9-gcc14-opt/share/dcube_IDTPMvsIDPVMPlots.xml
  * [4] output XML file = dcube_idtpm/dcube.xml
  * [5] log file        = dcube_idtpm/dcube.log
  *
  *  ***************************************************
  *  *                   !!! WARNINIG !!!              *
  *  * make sure that dcube.php is in PHP include path *
  *  ***************************************************
  *
  *
  *  ***************************************************
  *  *                   !!! WARNINIG !!!              *
  *  * make sure to put relative path from your result *
  *  * directory to the the directory with dcube.php   *
  *  ***************************************************/

error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT);
ini_set("display_errors", true);
ini_set("display_startup_errors", true);

/* ADD TO include_path TO LOCAL INSTALLATION OF DCUBE PHP PART */
$where = "DCubeServer";
set_include_path($where);
require "dcube.php";

$xml_file = "dcube.xml";
$log_file = "dcube.log";
$dcube = new dcube( $xml_file, $log_file, $where );
?>
