<?php
/**
  * DCubeClient PHP log file
  * autogenerated using DCube 7.5.1 by Krzysztof Daniel Ciba (Krzysztof.Ciba@NOSPAMgmail.com)
  * on Tue, 04 Aug 2026 17:04:49 CEST
  * Files:
  * [1] monitored file  = idtpm.HIST.root
  * [2] reference file  = physval_lrt.ntuple.IDTPMcnv.root
  * [3] config XML file = /eos/user/j/jlai/idtpm_validation/build/x86_64-el9-gcc14-opt/share/dcube_IDTPMvsIDPVMPlots.xml
  * [4] output XML file = dcube_idtpm_lrt/dcube.xml
  * [5] log file        = dcube_idtpm_lrt/dcube.log
  *
  *  ***************************************************
  *  *                   !!! WARNINIG !!!              *
  *  * make sure that dcube.php is in PHP include path *
  *  ***************************************************
  *
  *
  *  ***************************************************
  *  *                   !!! WARNINIG !!!              *
  *  * make sure to put relative path from your result *
  *  * directory to the the directory with dcube.php   *
  *  ***************************************************/

error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT);
ini_set("display_errors", true);
ini_set("display_startup_errors", true);

/* ADD TO include_path TO LOCAL INSTALLATION OF DCUBE PHP PART */
$where = "DCubeServer";
set_include_path($where);
require "rw.php";

$log_file = "dcube.log";
$page = new rainbow( $log_file );
?>
